# Generated by Django 5.2 on 2025-04-04 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_cliente_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='creado_en',
            field=models.DateField(auto_now_add=True),
        ),
    ]
