# Generated by Django 5.2 on 2025-04-04 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_alter_cliente_creado_en'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='creado_en',
        ),
    ]
